#spring配置
spring:
    #指定运行环境
    profiles:
        active: dev
    #数据库连接四要素
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #druid 数据源专有配置
        druid:
            #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
            initialSize: 5
            #最小连接池数量
            minIdle: 5
            #最大连接池数量
            maxActive: 20
            #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，
            #如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
            maxWait: 60000
            #1) Destroy线程会检测连接的间隔时间
            #2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
            timeBetweenEvictionRunsMillis: 60000
            #连接保持空闲而不被驱逐的最小时间
            minEvictableIdleTimeMillis: 300000
            #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
            #如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
            validationQuery: SELECT 1 FROM DUAL
            #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            testWhileIdle: true
            #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            testOnBorrow: false
            #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            testOnReturn: false
            #配置监控统计拦截的filters，stat:监控统计、wall：防御sql注入
            filters: stat,wall,config
            # 打开PSCache
            poolPreparedStatements: true
            #指定每个连接上PSCache的大小
            maxPoolPreparedStatementPerConnectionSize: 20
            #合并多个DruidDataSource的监控数据
            useGlobalDataSourceStat: true
            #通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #json序列化配置
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        serialization:
            write-dates-as-timestamps: false
    servlet:
        #配置文件上传
        multipart:
            enabled: true
            max-file-size: 100MB
            max-request-size: 200MB
    security:
        jwt:
            #token头的名称
            header: Authorization
            #token前缀
            prefix: "Bearer "
            #token加密规则
            secret: secret
            #token域名
            issuer: "http://127.0.0.1/"
            #过期时间1小时
            expiration: 3600
            #记住我过期时间7天
            remember: 604800
            #权限集合
            claimsAuthorities: authorities
            form-login: dhdhhdhdhdhdh
#mybatis plus配置
mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.javakc.islimp.modules.*.entity
    type-aliases-super-type: com.javakc.islimp.commons.base.entity.Base
    configuration:
        #启用驼峰命名
        map-underscore-to-camel-case: true
        #自动映射字段至属性
        auto-mapping-behavior: full
        #启用二级缓存
        cache-enabled: true